version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@1

jobs:
  build-and-test-project:
    working_directory: /go/src/github.com/Financial-Times/elasticsearch-reindexer
    docker:
      - image: golang:1
        environment:
          ELASTICSEARCH_TEST_URL: http://localhost:9200
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
      - image:  elasticsearch:7.10.1
        environment:
          discovery.type: single-node
    steps:
      - checkout
      - ft-golang-ci/build
      - ft-golang-ci/lint
      - ft-golang-ci/test

workflows:
  tests_and_docker:
    jobs:
      - build-and-test-project
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context: cm-team-snyk
