version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/elasticsearch-reindexer
    docker:
      - image: golang:1
        environment:
          GOPATH: /go
          ELASTICSEARCH_TEST_URL: http://localhost:9200
      - image:  elasticsearch:5.3
    steps:
      - checkout
      - run:
          name: External Dependencies
          command: |
            GO111MODULE=off go get github.com/mattn/goveralls
            GO111MODULE=off go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Test Results
          command: |
            mkdir -p /tmp/test-results	
            mkdir -p /tmp/coverage-results
      - run:
          name: Go Build
          command: go build -mod=readonly -v
      - run:
          name: Run Tests	
          command: |
            go test -mod=readonly -race -cover -coverprofile=/tmp/coverage-results/coverage.out ./... | go-junit-report > /tmp/test-results/main.xml
      - run:
          name: Combine Coverage Results
          command: |
            sed -i '1d' /tmp/coverage-results/*.out
            echo "mode: atomic" > /tmp/coverage-results/overall-coverage.result
            cat /tmp/coverage-results/*.out >> /tmp/coverage-results/overall-coverage.result
      - run:
          name: Upload Coverage
          command: goveralls -coverprofile=/tmp/coverage-results/overall-coverage.result -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-results
  dockerfile:
    working_directory: /elasticsearch-reindexer
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Dockerfile
          command: docker build .

workflows:
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
